name: PR clean-up

on:
  pull_request:
    types: [unlabeled, closed]

jobs:
  getStageName:
    if: |
      (github.event.action == 'unlabeled' && github.event.label.name == '🚀 deploy') ||
      (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, '🚀 deploy'))
    uses: ./.github/workflows/cdkPRStageName.yml

  pr-teardown:
    needs: getStageName
    concurrency:
      group: CDK-CD-PR-${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout the files
        uses: actions/checkout@v4

      - name: install node dependencies
        uses: bahmutov/npm-install@v1

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: destroy the stack on AWS
        run: npm run destroy
        env:
          STAGE: ${{ needs.getStageName.outputs.stage }}

      - name: deactivate github deployment
        uses: bobheadxi/deployments@v1
        with:
          step: delete-env
          token: "${{ secrets.TOME_GITHUB_STATUS_TOKEN }}"
          env: ${{ needs.getStageName.outputs.stage }}

      - name: removeLabel
        if: |
          (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, '🚀 deploy'))
        env:
          REPO: "${{ github.repository }}"
        run: |
          curl -L --silent --fail-with-body \
            -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            'https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels/%F0%9F%9A%80%20deploy'
